name: "yolov8_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 16

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 14, -1 ]
  }
]